version: '3.9'

services:
  nextjs:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: nextjs-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: